version: '3'
services:
  azprogs:
    environment:
      - APP_NAME=azprogs
      - UID=${HOST_UID:-0}
      - USER=${HOST_USER:-root}
    build:
      context: .
    volumes:
    - .:/app
    - ~/.azure:/home/.azure
